export declare function getLog(key: string): string;
export declare const codes: Readonly<{
    readonly JDB_DBINIT_INVPATH: "JDB_DBINIT_INVPATH";
    readonly JDB_DBINIT_INVALIDCONTROLFLOW: "JDB_DBINIT_INVALIDCONTROLFLOW";
    readonly JDB_DB_INVALIDCONTROLFLOW: "JDB_DB_INVALIDCONTROLFLOW";
    readonly JDB_INTERNAL_B64_WRONGINPUTSIZE1: "JDB_INTERNAL_B64_WRONGINPUTSIZE1";
    readonly JDB_INTERNAL_B64_WRONGINPUTSIZE2: "JDB_INTERNAL_B64_WRONGINPUTSIZE2";
    readonly JDB_DB_MKTABLE_F1: "JDB_DB_MKTABLE_F1";
    readonly JDB_DB_MKTABLE_EXISTS: "JDB_DB_MKTABLE_EXISTS";
    readonly JDB_DB_MKTRANSACTION_NOENTRY: "JDB_DB_MKTRANSACTION_NOENTRY";
    readonly JDB_DB_INTERNAL_MKTRANSACTION_MISSINGDATA: "JDB_DB_INTERNAL_MKTRANSACTION_MISSINGDATA";
    readonly JDB_TRANSACTION_INTERNAL_FAILEDTOCOMMIT_NOENTRY: "JDB_TRANSACTION_INTERNAL_FAILEDTOCOMMIT_NOENTRY";
    readonly JDB_TRANSACTION_RECOMMIT0: "JDB_TRANSACTION_RECOMMIT0";
    readonly JDB_TRANSACTION_CANCELTOOLATE0: "JDB_TRANSACTION_CANCELTOOLATE0";
    readonly JDB_TRANSACTION_COMMITTOOLATE0: "JDB_TRANSACTION_COMMITTOOLATE0";
    readonly JDB_TRANSACTION_RECANCEL: "JDB_TRANSACTION_RECANCEL";
    readonly JDB_DB_INTERNAL_SYNCTODISK_UNKNOWNFAILURE0: "JDB_DB_INTERNAL_SYNCTODISK_UNKNOWNFAILURE0";
}>;
//# sourceMappingURL=getlog.d.ts.map